(defun c:WT (/ dcl_id act)
  (vl-load-com)
  (setq dcl_file "D:\\WT3D_Project\\Z_Tools\\WT3D_AutoCAD_Studio_Panel.dcl")
  (if (not (findfile dcl_file))
    (setq dcl_file (findfile "WT3D_AutoCAD_Studio_Panel.dcl"))
  )
  
  (setq dcl_id (load_dialog dcl_file))
  (if (not (new_dialog "wt3d_dialog" dcl_id))
    (progn
      (princ "
❌ Không thể mở bảng giao diện WT3D!")
      (exit)
    )
  )
  
  (action_tile "btn_fast" "(done_dialog 1)")
  (action_tile "btn_purge" "(done_dialog 2)")
  (action_tile "btn_reset" "(done_dialog 3)")
  (action_tile "btn_v2u" "(done_dialog 4)")
  (action_tile "btn_sf" "(done_dialog 5)")
  (action_tile "cancel" "(done_dialog 0)")
  
  (setq act (start_dialog))
  (unload_dialog dcl_id)
  
  (cond
    ((= act 1)
      (if (findfile "D:\\WT3D_Project\\Z_Tools\\WT3D_Fast_AutoCAD_2025.lsp")
        (load "D:\\WT3D_Project\\Z_Tools\\WT3D_Fast_AutoCAD_2025.lsp")
      )
      (c:WT3D_FAST)
    )
    ((= act 2)
      (command "-purge" "all" "*" "n")
      (command "-purge" "regapps" "*" "n")
      (command "_.audit" "y")
      (princ "
🧹 [WT3D] ĐÃ DỌN SẠCH RÁC VÀ SỬA LỖI BẢN VẼ 100%!
")
    )
    ((= act 3)
      (if (findfile "D:\\WT3D_Project\\Z_Tools\\WT3D_Reset_AutoCAD_2025.lsp")
        (load "D:\\WT3D_Project\\Z_Tools\\WT3D_Reset_AutoCAD_2025.lsp")
      )
      (c:WT3D_RESET)
    )
    ((= act 4)
      (if (findfile "D:\\WT3D_Project\\Z_Tools\\WT3D_VNI_And_Unicode_Manager.lsp")
        (load "D:\\WT3D_Project\\Z_Tools\\WT3D_VNI_And_Unicode_Manager.lsp")
      )
      (c:V2U)
    )
    ((= act 5)
      (if (findfile "D:\\WT3D_Project\\Z_Tools\\WT3D_VNI_And_Unicode_Manager.lsp")
        (load "D:\\WT3D_Project\\Z_Tools\\WT3D_VNI_And_Unicode_Manager.lsp")
      )
      (c:SF)
    )
  )
  (princ)
)

(defun c:WT3D () (c:WT))
(defun c:W3D () (c:WT))
(princ "
🚀 [WT3D] BẢNG ĐIỀU KHIỂN NÚT BẤM ĐÃ SẴN SÀNG! GÕ LỆNH 'WT' HOẶC 'WT3D' ĐỂ MỞ BẢNG ĐIỀU KHIỂN!
")
(princ)
