; ==============================================================================
; WT3D PRO LISP: BANG DIEU KHIEN CHUYEN NGHIEP CHO AUTOCAD 2025
; Tac gia: Phan Trong Tan - WaterTreatment3D
; Khong loi: 100% Pure ASCII, Khong vuot qua 32 tham so cua AutoLISP
; ==============================================================================

;; -----------------------------------------------------------------------------
;; 1. HAM MO BANG DIEU KHIEN NUT BAM (GO LENH WT HOAC W3D)
;; -----------------------------------------------------------------------------
(defun c:WT (/ dcl_file f dcl_id act)
  (vl-load-com)
  
  (setq dcl_file (strcat (getvar "TEMPPREFIX") "wt3d_panel.dcl"))
  (setq f (open dcl_file "w"))
  (write-line "wt3d_dialog : dialog {" f)
  (write-line "  label = "WT3D STUDIO - AUTOCAD 2025";" f)
  (write-line "  spacer;" f)
  (write-line "  : text { label = "CHON TAC VU CAN THUC HIEN:"; alignment = centered; }" f)
  (write-line "  spacer;" f)
  (write-line "  : boxed_column {" f)
  (write-line "    label = "1. Hieu Nang & Toc Do";" f)
  (write-line "    : button { key = "btn1"; label = "1. Lam Nhe He Thong (0ms Delay, Muot)"; width = 45; height = 2; is_default = true; }" f)
  (write-line "    : button { key = "btn2"; label = "2. Don Rac & Sua Loi Ban Ve (Purge All)"; width = 45; }" f)
  (write-line "    : button { key = "btn3"; label = "3. Phuc Hoi Cai Dat Mac Dinh Goc"; width = 45; }" f)
  (write-line "  }" f)
  (write-line "  spacer;" f)
  (write-line "  : boxed_column {" f)
  (write-line "    label = "2. Font & Chu Tieng Viet (Unicode & VNI)";" f)
  (write-line "    : button { key = "btn4"; label = "4. Chuyen VNI -> Unicode Arial (Sua Loi)"; width = 45; height = 2; }" f)
  (write-line "    : button { key = "btn5"; label = "5. Quet Chon Vung & Doi Font Chu"; width = 45; }" f)
  (write-line "  }" f)
  (write-line "  spacer;" f)
  (write-line "  : button { key = "cancel"; label = "Dong"; is_cancel = true; alignment = centered; width = 16; }" f)
  (write-line "}" f)
  (close f)
  
  (setq dcl_id (load_dialog dcl_file))
  (if (new_dialog "wt3d_dialog" dcl_id)
    (progn
      (action_tile "btn1" "(done_dialog 1)")
      (action_tile "btn2" "(done_dialog 2)")
      (action_tile "btn3" "(done_dialog 3)")
      (action_tile "btn4" "(done_dialog 4)")
      (action_tile "btn5" "(done_dialog 5)")
      (action_tile "cancel" "(done_dialog 0)")
      (setq act (start_dialog))
      (unload_dialog dcl_id)
      (vl-file-delete dcl_file)
      
      (cond
        ((= act 1) (c:WT3D_FAST))
        ((= act 2)
          (command "-purge" "all" "*" "n")
          (command "-purge" "regapps" "*" "n")
          (command "_.audit" "y")
          (princ "\n[WT3D] Da don sach rac va sua loi ban ve thanh cong!\n")
        )
        ((= act 3) (c:WT3D_RESET))
        ((= act 4) (c:V2U))
        ((= act 5) (c:SF))
      )
    )
    (princ "\n[WT3D] Khong the khoi tao bang dieu khien!")
  )
  (princ)
)

(defun c:WT3D () (c:WT))
(defun c:W3D () (c:WT))

;; -----------------------------------------------------------------------------
;; 2. CAC HAM XU LY CHUYEN DUNG
;; -----------------------------------------------------------------------------

;; A. TOI UU HIEU NANG 0MS
(defun c:WT3D_FAST ()
  (vl-load-com)
  (setvar "VTDURATION" 0)
  (setvar "HPQUICKPREVIEW" 0)
  (setvar "HPMAXAREAS" 100)
  (setvar "SELECTIONCYCLING" 0)
  (setvar "ROLLOVERTOOLTIPS" 0)
  (setvar "SELECTIONEFFECT" 0)
  (setvar "PRESELECTIONEFFECT" 0)
  (setvar "LINESMOOTHING" 0)
  (setvar "INPUTSEARCHDELAY" 200)
  (setvar "DWGCHECK" 0)
  (setvar "INDEXCTL" 3)
  (setvar "XLOADCTL" 2)
  (setvar "CACHEMAXFILES" 256)
  (setvar "CACHEMAXTOTALSIZE" 1024)
  (setvar "PALETTEOPAQUE" 1)
  (setvar "OSMODE" 4287)
  (setvar "AUTOSNAP" 63)
  (setvar "POLARMODE" 2)
  (setvar "POLARANG" 45)
  (setvar "TRACKPATH" 0)
  (setvar "CURSORSIZE" 100)
  (setvar "APERTURE" 10)
  (setvar "GRIPSIZE" 5)
  (setvar "GRIPMULTIFUNCTION" 3)
  (setvar "PICKFIRST" 1)
  (setvar "PICKADD" 2)
  (setvar "EDGEMODE" 0)
  (setvar "DRAWORDERCTL" 3)
  (setvar "DIMASSOC" 2)
  (princ "\n[WT3D] DA TOI UU HOA HE THONG: 0ms DELAY + MUOT NHU BAY!\n")
  (princ)
)

;; B. PHUC HOI MAC DINH GOC
(defun c:WT3D_RESET ()
  (vl-load-com)
  (setvar "VTDURATION" 750)
  (setvar "HPQUICKPREVIEW" 1)
  (setvar "HPMAXAREAS" 100)
  (setvar "SELECTIONCYCLING" 0)
  (setvar "ROLLOVERTOOLTIPS" 1)
  (setvar "SELECTIONEFFECT" 1)
  (setvar "PRESELECTIONEFFECT" 1)
  (setvar "LINESMOOTHING" 1)
  (setvar "INPUTSEARCHDELAY" 500)
  (setvar "DWGCHECK" 1)
  (setvar "INDEXCTL" 0)
  (setvar "XLOADCTL" 1)
  (setvar "CACHEMAXFILES" 256)
  (setvar "CACHEMAXTOTALSIZE" 1024)
  (setvar "PALETTEOPAQUE" 0)
  (setvar "CURSORSIZE" 5)
  (princ "\n[WT3D] DA KHOI PHUC CAI DAT MAC DINH GOC CUA AUTODESK!\n")
  (princ)
)

;; C. CHUYEN VNI SANG UNICODE ARIAL
(defun c:V2U () (c:FIXALL))
(defun c:FIXALL (/ doc textStyles count ss i ent obj txtStr newStr blks blk atts)
  (vl-load-com)
  (setq doc (vla-get-ActiveDocument (vlax-get-acad-object)))
  (setq count 0)
  (setq textStyles (vla-get-TextStyles doc))
  (vlax-for st textStyles
    (vl-catch-all-apply 'vla-put-fontfile (list st "Arial.ttf"))
    (vl-catch-all-apply 'vla-put-BigFontFile (list st ""))
  )
  
  (setq ss (ssget "_X" '((0 . "TEXT,MTEXT"))))
  (if ss
    (progn
      (setq i 0)
      (while (< i (sslength ss))
        (setq ent (ssname ss i))
        (setq obj (vlax-ename->vla-object ent))
        (setq txtStr (vl-catch-all-apply 'vla-get-TextString (list obj)))
        (if (and txtStr (not (vl-catch-all-error-p txtStr)))
          (progn
            (setq newStr (wt3d-vni-convert txtStr))
            (if (/= newStr txtStr)
              (progn (vl-catch-all-apply 'vla-put-TextString (list obj newStr)) (setq count (1+ count)))
            )
          )
        )
        (setq i (1+ i))
      )
    )
  )
  
  (setq blks (ssget "_X" '((0 . "INSERT"))))
  (if blks
    (progn
      (setq i 0)
      (while (< i (sslength blks))
        (setq ent (ssname blks i))
        (setq obj (vlax-ename->vla-object ent))
        (if (= (vla-get-HasAttributes obj) :vlax-true)
          (progn
            (setq atts (vlax-safearray->list (vlax-variant-value (vla-GetAttributes obj))))
            (foreach att atts
              (setq txtStr (vla-get-TextString att))
              (setq newStr (wt3d-vni-convert txtStr))
              (if (/= newStr txtStr)
                (progn (vla-put-TextString att newStr) (setq count (1+ count)))
              )
            )
          )
        )
        (setq i (1+ i))
      )
    )
  )
  
  (command "_.regenall")
  (princ (strcat "\n[WT3D] DA CHUYEN DOI THANH CONG " (itoa count) " DOI TUONG VNI SANG UNICODE ARIAL!\n"))
  (princ)
)

;; Ham thay the chuoi con
(defun wt3d-rep (pat rep str / pos len)
  (setq len (strlen pat))
  (while (setq pos (vl-string-search pat str))
    (setq str (strcat (substr str 1 pos) rep (substr str (+ pos len 1))))
  )
  str
)

;; Chuyen doi VNI-Windows khong dung list lon
(defun wt3d-vni-convert (s)
  ;; A
  (setq s (wt3d-rep (strcat "A" (chr 217)) "\U+00C1" s))
  (setq s (wt3d-rep (strcat "A" (chr 216)) "\U+00C0" s))
  (setq s (wt3d-rep (strcat "A" (chr 219)) "\U+1EA2" s))
  (setq s (wt3d-rep (strcat "A" (chr 213)) "\U+00C3" s))
  (setq s (wt3d-rep (strcat "A" (chr 207)) "\U+1EA0" s))
  (setq s (wt3d-rep (strcat "a" (chr 249)) "\U+00E1" s))
  (setq s (wt3d-rep (strcat "a" (chr 248)) "\U+00E0" s))
  (setq s (wt3d-rep (strcat "a" (chr 251)) "\U+1EA3" s))
  (setq s (wt3d-rep (strcat "a" (chr 245)) "\U+00E3" s))
  (setq s (wt3d-rep (strcat "a" (chr 239)) "\U+1EA1" s))
  ;; E
  (setq s (wt3d-rep (strcat "E" (chr 217)) "\U+00C9" s))
  (setq s (wt3d-rep (strcat "E" (chr 216)) "\U+00C8" s))
  (setq s (wt3d-rep (strcat "E" (chr 219)) "\U+1EBA" s))
  (setq s (wt3d-rep (strcat "E" (chr 213)) "\U+1EBC" s))
  (setq s (wt3d-rep (strcat "E" (chr 207)) "\U+1EB8" s))
  (setq s (wt3d-rep (strcat "e" (chr 249)) "\U+00E9" s))
  (setq s (wt3d-rep (strcat "e" (chr 248)) "\U+00E8" s))
  (setq s (wt3d-rep (strcat "e" (chr 251)) "\U+1EBB" s))
  (setq s (wt3d-rep (strcat "e" (chr 245)) "\U+1EBD" s))
  (setq s (wt3d-rep (strcat "e" (chr 239)) "\U+1EB9" s))
  ;; O
  (setq s (wt3d-rep (strcat "O" (chr 217)) "\U+00D3" s))
  (setq s (wt3d-rep (strcat "O" (chr 216)) "\U+00D2" s))
  (setq s (wt3d-rep (strcat "O" (chr 219)) "\U+1ECE" s))
  (setq s (wt3d-rep (strcat "O" (chr 213)) "\U+00D5" s))
  (setq s (wt3d-rep (strcat "O" (chr 207)) "\U+1ECC" s))
  (setq s (wt3d-rep (strcat "o" (chr 249)) "\U+00F3" s))
  (setq s (wt3d-rep (strcat "o" (chr 248)) "\U+00F2" s))
  (setq s (wt3d-rep (strcat "o" (chr 251)) "\U+1ECF" s))
  (setq s (wt3d-rep (strcat "o" (chr 245)) "\U+00F5" s))
  (setq s (wt3d-rep (strcat "o" (chr 239)) "\U+1ECD" s))
  ;; U
  (setq s (wt3d-rep (strcat "U" (chr 217)) "\U+00DA" s))
  (setq s (wt3d-rep (strcat "U" (chr 216)) "\U+00D9" s))
  (setq s (wt3d-rep (strcat "U" (chr 219)) "\U+1EE6" s))
  (setq s (wt3d-rep (strcat "U" (chr 213)) "\U+0168" s))
  (setq s (wt3d-rep (strcat "U" (chr 207)) "\U+1EE4" s))
  (setq s (wt3d-rep (strcat "u" (chr 249)) "\U+00FA" s))
  (setq s (wt3d-rep (strcat "u" (chr 248)) "\U+00F9" s))
  (setq s (wt3d-rep (strcat "u" (chr 251)) "\U+1EE7" s))
  (setq s (wt3d-rep (strcat "u" (chr 245)) "\U+0169" s))
  (setq s (wt3d-rep (strcat "u" (chr 239)) "\U+1EE5" s))
  ;; Ky tu don
  (setq s (wt3d-rep (chr 209) "\U+0110" s))
  (setq s (wt3d-rep (chr 241) "\U+0111" s))
  (setq s (wt3d-rep (chr 214) "\U+01AF" s))
  (setq s (wt3d-rep (chr 246) "\U+01B0" s))
  (setq s (wt3d-rep (chr 212) "\U+01A0" s))
  (setq s (wt3d-rep (chr 244) "\U+01A1" s))
  s
)

;; D. QUET VUNG VA DOI FONT
(defun c:SF (/ ss opt fontFile styleName doc acadObj i ent obj count textStyles targetStyle atts entType)
  (vl-load-com)
  (setq acadObj (vlax-get-acad-object))
  (setq doc (vla-get-ActiveDocument acadObj))
  (princ "\nQUET CHON CAC DOI TUONG CHU (HOAC NHAN ENTER DE CHON TAT CA): ")
  (setq ss (ssget '((0 . "TEXT,MTEXT,INSERT,DIMENSION"))))
  (if (not ss) (setq ss (ssget "_X" '((0 . "TEXT,MTEXT,INSERT,DIMENSION")))))
  (if (not ss) (progn (princ "\nKhong tim thay doi tuong chu!") (exit)))
  (princ "\n[1] Arial.ttf | [2] Times New Roman | [3] VNI-Times | [4] VNI-Helve | [5] Khac")
  (initget "1 2 3 4 5")
  (setq opt (getkword "\nNhap lua chon [1/2/3/4/5] <1 - Arial>: "))
  (if (not opt) (setq opt "1"))
  (cond
    ((= opt "1") (setq fontFile "Arial.ttf" styleName "WT3D_Arial"))
    ((= opt "2") (setq fontFile "times.ttf" styleName "WT3D_Times"))
    ((= opt "3") (setq fontFile "VNI-Times.ttf" styleName "WT3D_VNI_Times"))
    ((= opt "4") (setq fontFile "VNI-Helve.ttf" styleName "WT3D_VNI_Helve"))
    ((= opt "5") (setq fontFile (getstring "\nNhap ten font: ") styleName (strcat "WT3D_" (vl-filename-base fontFile))))
  )
  (setq textStyles (vla-get-TextStyles doc))
  (setq targetStyle (vl-catch-all-apply 'vla-Item (list textStyles styleName)))
  (if (vl-catch-all-error-p targetStyle)
    (progn (setq targetStyle (vla-Add textStyles styleName)) (vl-catch-all-apply 'vla-put-fontfile (list targetStyle fontFile)))
    (vl-catch-all-apply 'vla-put-fontfile (list targetStyle fontFile))
  )
  (setq count 0 i 0)
  (while (< i (sslength ss))
    (setq ent (ssname ss i))
    (setq obj (vlax-ename->vla-object ent))
    (setq entType (vla-get-ObjectName obj))
    (if (or (= entType "AcDbText") (= entType "AcDbMText"))
      (progn (vl-catch-all-apply 'vla-put-StyleName (list obj styleName)) (setq count (1+ count)))
    )
    (if (= entType "AcDbBlockReference")
      (if (= (vla-get-HasAttributes obj) :vlax-true)
        (progn
          (setq atts (vlax-safearray->list (vlax-variant-value (vla-GetAttributes obj))))
          (foreach att atts (vl-catch-all-apply 'vla-put-StyleName (list att styleName)) (setq count (1+ count)))
        )
      )
    )
    (setq i (1+ i))
  )
  (command "_.regenall")
  (princ (strcat "\n[WT3D] DA DOI THANH CONG " (itoa count) " DOI TUONG SANG FONT: " fontFile "!\n"))
  (princ)
)

;; Tu dong mo bang ngay khi nap file
(c:WT)
