(defun c:WT3D_FAST ()
  (vl-load-com)
  (mapcar '(lambda (x) (vl-catch-all-apply 'setvar x))
    '(("VTDURATION" 0)
      ("HPQUICKPREVIEW" 0)
      ("HPMAXAREAS" 100)
      ("SELECTIONCYCLING" 0)
      ("ROLLOVERTOOLTIPS" 0)
      ("SELECTIONEFFECT" 0)
      ("PRESELECTIONEFFECT" 0)
      ("LINESMOOTHING" 0)
      ("INPUTSEARCHDELAY" 300)
      ("DWGCHECK" 0)
      ("INDEXCTL" 3)
      ("XLOADCTL" 2)
      ("CACHEMAXFILES" 256)
      ("CACHEMAXTOTALSIZE" 1024)
      ("PALETTEOPAQUE" 1))
  )
  (princ "
🚀 [WT3D] ĐÃ TỐI ƯU HÓA AUTOCAD 2025 SIÊU NHẸ & 0ms DELAY THÀNH CÔNG!
")
  (princ)
)
(c:WT3D_FAST)
